spring:
  profiles:
    active: dev
  application:
    name: spring-boot-config
  server:
    port: 8080
    context-path: /

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xc.roadRisk.assessment

snowflake:
  workerId: 0
  datacenterId: 0

jdbc:
  type: mysql

